### ISSUE TITLE
User can search for a specific Pokemon.

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a specific Pokemon. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A search bar will open to allow the user to search for a Pokemon. Partial spelling will display all Pokemon that have the search input in their name.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/121611832-00667680-ca0e-11eb-874c-df0c7da321a2.png)
![image](https://user-images.githubusercontent.com/58172952/121611849-0ceacf00-ca0e-11eb-96d8-393300b9c4db.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create top nav bar with the search button.
- [x] Have search button listen for 'click' event to open search bar.
- [x] Add a 'div[data-view="search-pokemon"]' to the HTML.
- [x] Add a search bar and button.
- [x] Ensure the search bar looks nice on both mobile-sized and desktop-sized screens.
- [x] Make search input required.
- [x] Show error message if Pokemon can't be found.
- [x] Add a 'div[data-view="view-pokemon"]' to the HTML.
- [x] Add an empty unordered list to the 'div[data-view="view"]' element in the HTML.
- [x] Add a dummy pokemon to the unordered list in HTML and style them to match the wireframe.
- [x] Ensure dummy pokemon looks nice on both mobile-sized and desktop-sized screens.
- [x] Define a function that listens for which search result is clicked and makes a request to the API to get data for that pokemon to append a DOM tree to the unordered list on 'div[data-view="view-pokemon"]'.
- [x] Remove dummy pokemon from HTML.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
