### ISSUE TITLE
Feature: Users can search for anime by name. 

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for anime by name. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to search for an anime and then click on a specific result to see more info about it including a synopsis.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/114919681-669f9600-9ddd-11eb-95f4-6b8e6bb4c842.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Listen for "click" event on the search text link or search icon to pop up a search bar.
- [ ] Make input for search bar form "required"
- [ ] Listen for "submit" event on the search button below the search bar to request data from API.
- [ ] Display search results in a new object.
  - [ ] Only show image url, title, type, episodes quantity from API for search results list.
  - [ ] Ensure star is empty if anime is not a favorite (yet).
  - [ ] Listen for "click" event on title or image of a search result to open that anime.
    - [ ] Display the anime based on the id# from the search results.
    - [ ] Show image, title, type, episodes, status, rating, and aired dates from API.
    - [ ] Ensure star is empty if not a favorite (yet).
    - [ ] Ensure stars for ratings are empty since it can only be rated after favoriting.
    - [ ] Display a synopsis from the API.
    - [ ] Make sure that click targets are either `<a>` or `<button>` elements.
    - [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
