### ISSUE TITLE
User can view the Pokemon's evolution tree.

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/122269326-f02d1c00-ce91-11eb-944b-a7446e0d079f.png)
![image](https://user-images.githubusercontent.com/58172952/122269373-fc18de00-ce91-11eb-8526-fa6ad321923d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create dummy evolution entries in data-view="view-pokemon"
- [x] Style dummy evolution entries to look good on both mobile and desktop
- [ ] Write function to request api data for the evolution tree.
- [ ] Check special evolutions like eevee and other Pokemon that have irregular evolutions.
- [ ] Remove dummy evolution entries.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
