### ISSUE TITLE
Refactor: Refactor to ES6

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/ajax-project#9]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] ... 
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
